#!/bin/sh

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -use-ocamlfind -classic-display \
                                     -tag debug"}

action ()
{
    case $1 in
        default)    action lib ;;
        lib)        $OCAMLBUILD misc.cma ;;
        doc)        $OCAMLBUILD doc/lib.docdir/index.html ;;
        clean)      $OCAMLBUILD -clean ;;
        sanity)     ocamlfind query unix ;;
        *)          $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
