#!/bin/sh

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -use-ocamlfind -classic-display \
                                     -tag debug"}

run_test ()
{
    SERVER_NAME=$(hostname -s)
    ../client/build bin-native
    ./server.native 8500 grep "$USER" &
    SERVER_PID=$!
    EXPECTED=$(grep $USER </etc/passwd)
    ACTUAL=$(../client/client.native $SERVER_NAME 8500 </etc/passwd)
    kill -9 $SERVER_PID
    if test "$EXPECTED" = "$ACTUAL"
    then
        echo "Test passed!"
    else
        echo "Test failed!"
        exit 2
    fi
}

action ()
{
    case $1 in
        default)    action bin-native ;;
        bin-byte)   $OCAMLBUILD server.byte ;;
        bin-native) $OCAMLBUILD server.native ;;
        tests)      action bin-native && run_test ;;
        clean)      $OCAMLBUILD -clean ;;
        *)          $OCAMLBUILD $* ;;
    esac
}

cd $(dirname $0)

if [ $# -eq 0 ];
then action default ;
else action $*; fi
