image: debian/stable
packages:
  - build-essential
  - ocaml
  - opam
  - m4
  - darcs
  - rsync
sources:
  - https://git.sr.ht/~henrytill/ocamlunix
tasks:
  - opam-init: |
      opam init -yaq
  - opam-switch: |
      eval $(opam env)
      opam switch create 4.13.0
      opam switch set 4.13.0
  - opam-install: |
      eval $(opam env)
      cd ocamlunix
      opam install -yq --deps-only --with-test .
  - build: |
      eval $(opam env)
      cd ocamlunix
      dune build
  - test: |
      eval $(opam env)
      cd ocamlunix
      dune test --force
