#! /usr/bin/env bash

set -euo pipefail

BINARY_DEPENDENCIES=(
    "ocamlfind"
    "ocamlbuild"
)

LIBRARY_DEPENDENCIES=(
    "alcotest"
)

OPAM_INSTALL=${OPAM_INSTALL:="opam install -y"}

BUILD_SCRIPTS=$(find . -mindepth 2 -type f -name build -exec test -x {} \; -print | sort)

check_bin ()
{
    command -v $1 || $OPAM_INSTALL $1
}

check_lib ()
{
    ocamlfind query $1 || $OPAM_INSTALL $1
}

check_deps ()
{
    for bindep in ${BINARY_DEPENDENCIES[@]}
    do
        check_bin $bindep
    done

    for libdep in ${LIBRARY_DEPENDENCIES[@]}
    do
        check_lib $libdep
    done
}

every ()
{
    for script in $BUILD_SCRIPTS; do
        echo $script $*
        $script $*
    done
}

action ()
{
    case $1 in
        default) action deps && every ;;
        deps)    check_deps ;;
        tests)   action deps && every tests ;;
        clean)   every clean ;;
        *)       every $* ;;
    esac
}

cd $(dirname $0)

if [ $# -eq 0 ];
then action default ;
else action $*; fi
