#!/bin/sh

set -e

cd $(dirname $0)

OPAM_INSTALL="opam install -y"

DEPENDENCIES="alcotest"

BUILD_SCRIPTS=$(find . -mindepth 2 -type f -name build -exec test -x {} \; -print | sort)

check_bin ()
{
    command -v $1 || $OPAM_INSTALL $1
}

check_libs ()
{
    ocamlfind query $* || $OPAM_INSTALL $*
}

check_deps ()
{
    check_bin ocamlfind
    check_bin ocamlbuild
    check_libs $DEPENDENCIES
}

every ()
{
    for script in $BUILD_SCRIPTS; do
        echo $script $*
        $script $*
    done
}

action ()
{
    case $1 in
        default) action deps && every ;;
        deps)    check_deps ;;
        tests)   action deps && every tests ;;
        clean)   every clean ;;
        *)       every $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
