#!/bin/sh

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -use-ocamlfind -classic-display \
                                     -tag debug"}

action ()
{
    case $1 in
        default)
            action bin-native
            ;;
        bin-byte)
            $OCAMLBUILD find.byte
            $OCAMLBUILD exercise1.byte
            $OCAMLBUILD getcwd.byte
            ;;
        bin-native)
            $OCAMLBUILD find.native
            $OCAMLBUILD exercise1.native
            $OCAMLBUILD getcwd.native
            ;;
        test)
            action default
            [ "$(./getcwd.native)" = "$(pwd)" ] && echo TEST PASSED!
            ;;
        clean)
            $OCAMLBUILD -clean
            ;;
        *)
            $OCAMLBUILD $*
            ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
