#!/bin/sh

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -use-ocamlfind -classic-display \
                                     -tag debug"}

action ()
{
    case $1 in
        default)
            action bin-native
            ;;
        bin-byte)
            $OCAMLBUILD readtar_v1.byte
            $OCAMLBUILD readtar_v2.byte
            $OCAMLBUILD untar.byte
            $OCAMLBUILD tar.byte
            ;;
        bin-native)
            $OCAMLBUILD readtar_v1.native
            $OCAMLBUILD readtar_v2.native
            $OCAMLBUILD untar.native
            $OCAMLBUILD tar.native
            ;;
        test)
            action default
            ;;
        clean)
            $OCAMLBUILD -clean
            ;;
        *)
            $OCAMLBUILD $*
            ;;
    esac
}

cd $(dirname $0)

if [ $# -eq 0 ];
then action default ;
else action $*; fi
