#!/bin/sh

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -use-ocamlfind -classic-display \
                                     -tag debug"}

action ()
{
    case $1 in
        default)    action bin-native ;;
        bin-byte)   $OCAMLBUILD sieve.byte ;;
        bin-native) $OCAMLBUILD sieve.native ;;
        tests)      action default ;;
        clean)      $OCAMLBUILD -clean ;;
        *)          $OCAMLBUILD $* ;;
    esac
}

cd $(dirname $0)

if [ $# -eq 0 ];
then action default ;
else action $*; fi
