#!/bin/sh

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -use-ocamlfind -classic-display \
                                     -tag debug"}

action ()
{
    case $1 in
        default)    action bin-native ;;
        bin-byte)   $OCAMLBUILD echo.byte ;;
        bin-native) $OCAMLBUILD echo.native ;;
        test)       action bin-native && ./echo.native '[1, 2, "three", {"four": 4}]' ;;
        clean)      $OCAMLBUILD -clean ;;
        *)          $OCAMLBUILD $* ;;
    esac
}

cd $(dirname $0)

if [ $# -eq 0 ];
then action default ;
else action $*; fi
