#!/bin/sh

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -use-ocamlfind -classic-display \
                                     -tag debug"}

assert_equals ()
{
    if test $1 = $2
    then
        echo "Test passed."
        exit 0
    else
        echo "$1 is not equal to $2"
        echo "Test failed."
        exit 1
    fi
}

run_tests ()
{
    EXPECTED=$(echo quux | sha256sum | cut -d ' ' -f1)
    ACTUAL=$(./compose.native "echo quux" "sha256sum" "cut -d ' ' -f1")
    assert_equals $EXPECTED $ACTUAL
}

action ()
{
    case $1 in
        default)    action bin-native ;;
        bin-byte)   $OCAMLBUILD compose.byte ;;
        bin-native) $OCAMLBUILD compose.native ;;
        tests)      action bin-native && run_tests ;;
        clean)      $OCAMLBUILD -clean ;;
        *)          $OCAMLBUILD $* ;;
    esac
}

cd $(dirname $0)

if [ $# -eq 0 ];
then action default ;
else action $*; fi
